AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'support/**/*'
    - 'tmp/**/*'
    - 'test/**/*'

ConditionalAssignment:
  Enabled: false
StringLiterals:
  Enabled: false
RedundantReturn:
  Enabled: false
Documentation:
  Enabled: false
WordArray:
  Enabled: false
AbcSize:
  Enabled: false
MutableConstant:
  Enabled: false
SignalException:
  Enabled: false
Casecmp:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
MissingRespondToMissing:
  Enabled: false
MethodMissingSuper:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
LineLength:
  Max: 120
Style/EmptyMethod:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space
Style/Lambda:
  EnforcedStyle: literal
Style/SymbolArray:
  EnforcedStyle: brackets
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
